### ISSUE TITLE
Dependency on postgres

### ISSUE THREAD

**Issue by archie** [Sandthorn/sandthorn_driver_sequel#1]
Is [this dependency](https://github.com/Sandthorn/sandthorn_driver_sequel/blob/master/sandthorn_driver_sequel.gemspec#L38) required for the sequel driver? If not, can it be removed for simplicity's sake?

**Comment by larskrantz** [comment]
Good point, it should be safe to be remove - in a production env you must
include the correct gem depending on your dbtype.

**Comment by archie** [comment]
LGTM
